language: python
python:
  - "3.7"

install:
  - pip install nose rednose coverage coveralls

script:
  - nosetests --verbose --rednose --with-coverage --cover-erase --cover-package=derivatex

after_success:
  - coveralls

notifications:
  email: false